### ISSUE TITLE
Ladka nepracuje

### ISSUE THREAD

**Issue by neluse** [frenzymadness/prezencka#16]
![15145125_10206622721799938_1908787492_o](https://cloud.githubusercontent.com/assets/23662932/20537965/8291ca0c-b0ef-11e6-80f2-50a0da840f97.jpg)

**Comment by ladula** [comment]
Mazani mailu je tezka prace, obzvlaste kdyz je jich 1000 :/

**Comment by frenzymadness** [comment]
:+1: za snahu pro @ladula
